#try:
#    def fun():
#        print('hi')
#    #fun()
#    print(fun())
#except Exception as fool:
                     
#    pass
